# Generated by Django 4.0.6 on 2022-09-09 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usluga_payment", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Podiezd",
        ),
    ]
